version: "2"

services:
  web:
    image: nginx:latest
    container_name: client
    ports:
      - "8000:80"
    volumes:
      - ./app:/device-detector
      - ./site.conf:/etc/nginx/conf.d/default.conf
